services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./custom-config.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx

volumes:
  html:
  logs: